# Generated by Django 3.1.5 on 2021-01-27 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='manufacturer',
            field=models.OneToOneField(limit_choices_to={'role': 'manufacturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production', to='core.player'),
        ),
    ]
