# Generated by Django 3.1.5 on 2021-01-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210126_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='crown_balance',
        ),
        migrations.AddField(
            model_name='gamesetting',
            name='number_of_brokers',
            field=models.PositiveIntegerField(default=3, verbose_name='Количество маклеров в сессии'),
        ),
        migrations.AlterField(
            model_name='gamesetting',
            name='crown_balance',
            field=models.PositiveIntegerField(default=12000, verbose_name='Баланс короны'),
        ),
    ]
