# Generated by Django 3.1.5 on 2021-01-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210126_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='player_count',
            field=models.IntegerField(default=14, verbose_name='количество игроков'),
        ),
    ]
