# Generated by Django 3.1.5 on 2021-01-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210126_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesetting',
            name='turn_time_preset',
            field=models.TextField(default={}),
        ),
    ]
