# Generated by Django 3.1.5 on 2021-01-26 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_session_player_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn', to='core.session', verbose_name='Сессия'),
        ),
    ]
