# Generated by Django 3.1.5 on 2021-01-27 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210126_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='turn',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='core.turn'),
        ),
    ]
