# Generated by Django 3.1.5 on 2021-01-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210127_0611'),
        ('core', '0011_gamesetting_turn_time_preset'),
    ]

    operations = [
    ]
