# Generated by Django 3.1.5 on 2021-01-27 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20210127_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesetting',
            name='turn_time_preset',
            field=models.TextField(default={1: 15, 2: 10, 3: 10, 4: 10, 5: 7, 6: 7, 7: 7, 8: 7, 9: 7, 10: 7}),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='turn',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='core.turn'),
        ),
    ]
