# Generated by Django 3.1.5 on 2021-01-27 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210127_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesetting',
            name='session',
        ),
        migrations.AddField(
            model_name='session',
            name='settings',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session', to='core.gamesetting'),
        ),
    ]
