# Generated by Django 3.1.5 on 2021-01-27 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210127_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='timer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turn', to='core.turncountdowntimer', verbose_name='Таймер хода'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='player',
            field=models.OneToOneField(limit_choices_to={'role': 'manufacturer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse', to='core.player'),
        ),
    ]
